[project]
name = "advent-of-code-2015"
version = "0.1.0"
description = "Solutions for Advent of Code 2015."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "numpy>=2.3.1",
    "scipy>=1.16.0",
]
